[build-system]
requires = ["setuptools>=61", "wheel>=0.36"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen-42"
version = "1.0.0"
description = "Core maze generation library for A-Maze-Ing project"
readme = "README.md"
requires-python = ">=3.10"

authors = [
  { name = "Jayesh Manani (jmanani)" },
  { name = "Mariia Lagutina (mlagutin)" }
]

dependencies = []

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen"]
