[build-system]
requires = ["setuptools>=61", "wheel>=0.36"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "Core maze generation library for A-Maze-Ing project"
readme = "README.md"
requires-python = ">=3.10"

authors = [
  { name = "Jayesh Manani (jmanani)" },
  { name = "Mariia Lagutina (mlagutin)" }
]

dependencies = []

[tool.setuptools]
package-dir = {"mazegen" = "."}
packages = ["mazegen"]
include-package-data = true

[tool.setuptools.package-data]
mazegen = ["README.md"]